### PR TITLE
Add documentation for Ember integration

### PR DESCRIPTION
**Pull request by jlevycpa**
Adding ember integration to docs per https://github.com/apollostack/apollo/issues/41

### CODE REVIEW

**Comment by stubailo** [comment]
Make sure to add it to config.yml! I'd run the site locally to make sure it works.

**Comment by helfer** [comment]
@jlevycpa * bump *

**Comment by jlevycpa** [comment]
Sorry for the delay!

**Comment by helfer** [comment]
Thanks @jlevycpa ! 🙂

**Pull request merged**
