### PR TITLE
Adds vue.js to integrations section

### PR DESCRIPTION
**Pull request by zol**
@stubailo What do you think of adding integrations like this? Another option might be to have an 'Other' or 'External' sibling to 'Meteor' and simply list them in there.

### CODE REVIEW

**Comment by stubailo** [comment]
I like it! I'd say let's not shy away from adding more stuff here.

**Comment by zol** [comment]
Perfect, agreed. This way integrations will show up prominently in the sidebar.

**Comment by aruntk** [comment]
@zol @stubailo [polymer apollo integration](https://github.com/aruntk/polymer-apollo)

**Comment by stubailo** [comment]
Mind opening a similar PR about it?

**Comment by aruntk** [comment]
@stubailo sure. :)

**Pull request merged**
